FROM node:latest as build-stage
WORKDIR /usr/src/app
COPY package*.json ./
RUN npm install
COPY ./ .
RUN npm run build

FROM nginx as production-stage
RUN mkdir /app
COPY --from=build-stage /app/dist /usr/src/app/html
COPY default.conf /etc/nginx/conf.d