version: '3.7'

services:
  api:
    build:
      context: ../backend/back_store
      dockerfile: Dockerfile
    container_name: DRF
    restart: always
    command: bash entrypoint.sh
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ../backend/back_store/.env.dev
    depends_on:
      - db

  db:
    image: postgres:12
    container_name: backend_db
    volumes:
      - type: volume
        source: pgdata_dev
        target: /var/lib/postgresql/data
    env_file:
      - ../backend/back_store/.env.dev
    ports:
      - 5432:5432


volumes:
  static:
  media:
  pgdata_dev:
    external: true