version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile_prod
    container_name: frontend_prod
    volumes:
      - static:/usr/share/nginx/static
      - media:/usr/share/nginx/media
      - ssl_nginx:/etc/nginx/ssl
    ports:
      - 80:80
      - 443:443
    expose:
      - 80
      - 443
    depends_on:
      - backend_api

  backend_api:
    build:
      context: ../backend/back_store
      dockerfile: Dockerfile
    container_name: DRF
    restart: always
    command: bash entrypoint_prod.sh
    environment:
      - REDIS_HOST=redis
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 8000:8000
    env_file:
      - ../backend/back_store/.env.prod
    depends_on:
      - backend_db


  backend_db:
    image: postgres:12
    container_name: backend_db
    volumes:
      - type: volume
        source: pgdata
        target: /var/lib/postgresql/data
    env_file:
      - ../backend/back_store/.env.prod
    ports:
      - 5432:5432


  redis:
    restart: always
    image: redis:latest
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

volumes:
  pgdata:
    external: true
  static:
  media:
  ssl_nginx:
    external: true
  redis_data:
