version: '3.7'

services:
  frontend:
    build: ../frontend
    container_name: frontend_prod
    ports:
      - 8080:8080
    volumes:
      - dist:/app/dist
    expose:
      - 8080

  nginx:
    build: ../backend/nginx
    container_name: nginx
    ports:
      - 80:80
    restart: on-failure
    volumes:
      - dist:/usr/share/nginx/html/
    depends_on:
      - frontend

volumes:
  dist:
