version: '3.7'

services:
  frontend:
    build:
      context: ../frontend
      dockerfile: Dockerfile_prod
    container_name: frontend_prod
    volumes:
      - static:/usr/src/app/static
      - media:/usr/src/app/media
    ports:
      - 80:80
    expose:
      - 80

volumes:
  static:
  media: