# Generated by Django 4.1.3 on 2022-12-13 14:58

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('611e6cde-6a87-4646-ba40-41287dcdd474'), primary_key=True, serialize=False),
        ),
    ]
