# Generated by Django 4.1.3 on 2022-12-13 15:00

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('ac55a3cd-693e-442d-b9db-f0aa4ba6a9a2'), primary_key=True, serialize=False),
        ),
    ]
