# Generated by Django 4.1.3 on 2022-12-13 15:01

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('94a306e2-b6e2-4942-bac2-0c5ee68f7184'), primary_key=True, serialize=False),
        ),
    ]
