# Generated by Django 4.1.3 on 2022-12-13 15:08

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a9243b6e-fe04-459e-b24f-62a9a0976ea1'), primary_key=True, serialize=False),
        ),
    ]
