# Generated by Django 4.1.3 on 2022-12-13 15:15

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('93dbd949-7725-49ef-a646-2a446067afc0'), primary_key=True, serialize=False),
        ),
    ]
