# Generated by Django 4.1.3 on 2022-12-13 15:20

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f9328693-ed6a-4ab1-83e0-e85cf6aa80e5'), primary_key=True, serialize=False),
        ),
    ]
