# Generated by Django 4.1.3 on 2022-12-13 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8a5c35a5-6744-4739-bae7-63c59704f426'), primary_key=True, serialize=False),
        ),
    ]
