# Generated by Django 4.1.3 on 2022-12-13 15:22

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('9abc6e5d-afe2-4468-bf9a-9b19335cade7'), primary_key=True, serialize=False),
        ),
    ]
