# Generated by Django 4.1.3 on 2022-12-13 15:24

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('f70806fa-74d7-4099-b2d2-90dcce43dcee'), primary_key=True, serialize=False),
        ),
    ]
