# Generated by Django 4.1.3 on 2022-12-13 16:59

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0012_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('a10fa76b-ddc1-49db-b965-da5dae2035e6'), primary_key=True, serialize=False),
        ),
    ]
