# Generated by Django 4.1.3 on 2022-12-14 10:04

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_alter_cart_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='id',
            field=models.UUIDField(default=uuid.UUID('4f5c20a1-0ef1-45da-a737-57d968848d4f'), primary_key=True, serialize=False),
        ),
    ]
