name: Build and deploy workflow
on: [push]
jobs:
  deploy_on_push:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Deploy on Server
        uses: appleboy/ssh-action@v0.1.4
        with:
          host: ${{ secrets.First_VDS_SSH_HOST }}
          username: ${{ secrets.First_VDS_SSH_USERNAME }}
          password: ${{ secrets.First_VDS_SSH_PASSWORD }}
          port: ${{ secrets.First_VDS_SSH_PORT }}
          script: |
            cd portfolio/compose
            git pull
            echo $ {{ secrets.First_VDS_SSH_PASSWORD }} | sudo -S docker-compose -f docker-compose_prod.yml up --build -d
            sudo docker ps