# Generated by Django 4.1.2 on 2022-10-30 21:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_product_attrs'),
    ]

    operations = [
        migrations.CreateModel(
            name='product_attr_value',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=255)),
                ('opt_value', models.CharField(blank=True, max_length=255, null=True)),
                ('attrs_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product_attrs')),
                ('product_id', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='shop.product')),
            ],
        ),
    ]
