# Generated by Django 4.1.2 on 2022-10-30 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_product_attr_value'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_attr_value',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product_attr_value',
            name='product_id',
            field=models.ManyToManyField(to='shop.product'),
        ),
    ]
