# Generated by Django 4.1.2 on 2022-10-31 12:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_remove_product_attr_value_product_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product_attr_value',
            name='product_id',
        ),
        migrations.AddField(
            model_name='product',
            name='attr_value',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='shop.product_attr_value'),
        ),
    ]
