# Generated by Django 4.1.2 on 2022-11-08 09:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_alter_productadditionals_prod_option_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productadditionals',
            name='product',
        ),
        migrations.AddField(
            model_name='productadditionals',
            name='product',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='additionals', to='shop.product'),
        ),
    ]
