# Generated by Django 4.1.2 on 2022-11-09 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0012_remove_productadditionals_product_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productadditionals',
            name='prod_variants',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productadditionals',
            name='prod_variants2',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productadditionals',
            name='prod_variants3',
            field=models.TextField(blank=True, null=True),
        ),
    ]
