# Generated by Django 4.1.3 on 2022-11-16 08:12

from django.db import migrations, models
import django.db.models.deletion
import shop.models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0017_product_product_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='images',
            field=models.ImageField(blank=True, null=True, upload_to=shop.models.product_picture_directory_path),
        ),
        migrations.CreateModel(
            name='ProductMaxVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, null=True)),
                ('icon', models.ImageField(blank=True, null=True, upload_to=shop.models.product_picture_directory_path)),
                ('description', models.TextField(null=True)),
                ('product', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.product')),
            ],
        ),
    ]
