# Generated by Django 4.1.3 on 2022-12-14 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0021_subcategory'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='seat',
            field=models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], default='нет', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='product',
            name='winter',
            field=models.CharField(blank=True, choices=[('yes', 'да'), ('no', 'нет')], default='нет', max_length=255, null=True),
        ),
    ]
