# Generated by Django 4.1.3 on 2022-12-14 17:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0022_product_seat_product_winter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='seat',
        ),
        migrations.RemoveField(
            model_name='product',
            name='winter',
        ),
    ]
