# Generated by Django 4.1.3 on 2022-12-14 17:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0023_remove_product_seat_remove_product_winter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subcategory',
            name='value',
        ),
        migrations.CreateModel(
            name='SubCategoryItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item', models.CharField(blank=True, max_length=120, null=True)),
                ('subcategory', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.subcategory')),
            ],
        ),
    ]
