# Generated by Django 4.1.3 on 2022-12-20 08:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0024_remove_subcategory_value_subcategoryitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subcategory',
            name='category',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='submenu', to='shop.category', to_field='slug'),
        ),
        migrations.AlterField(
            model_name='subcategoryitem',
            name='subcategory',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='item', to='shop.subcategory'),
        ),
    ]
