# Generated by Django 4.1.3 on 2022-12-22 11:48

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_subcategory_category_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productstatus',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productstatus', to='shop.product'),
        ),
        migrations.CreateModel(
            name='FiltersByCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('alias', models.SlugField(blank=True, max_length=255, unique=True)),
                ('options', django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=200), blank=True, size=None)),
                ('category', models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, related_name='filter', to='shop.category', to_field='slug')),
            ],
        ),
    ]
